steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/auto-redirect', '.']

  # Step 2: Push the Docker image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/auto-redirect']

  # Step 3: Deploy the image to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['run', 'deploy', 'auto-redirect',
           '--image', 'gcr.io/$PROJECT_ID/auto-redirect',
           '--platform', 'managed',
           '--region', 'us-central1',
           '--allow-unauthenticated']

images:
  - 'gcr.io/$PROJECT_ID/auto-redirect'